### PR TITLE
Refactor graphics settings

### PR DESCRIPTION
**Pull request by jac32**
- Via builder pattern
- Color not fully implemented

### CODE REVIEW

**Comment by jac32** [comment]
Options parsing now done using the `getopts` crate.
parse_settings function is ugly, looking into improvements.

**Comment by f-prettyland** [comment]
Okay this is actually much nicer for the parsing. Ta

**Comment by f-prettyland** [comment]
Though it doesn't compile, you left an old var in

**Comment by f-prettyland** [comment]
Also; isn't having to clone this struct for every thread pretty bad?

**Comment by f-prettyland** [comment]
Small tests suggest variables are slightly better so I have changed to use these, struct is still used for function calling, just means less cloning needed.

```
bash-4.3$ time ./geofracVars 2 0.001 30 2

real    5m2.380s
user    3m25.318s
sys 5m57.734s
bash-4.3$ time ./geofracStruct 2 0.001 30 2

real    5m31.974s
user    3m19.769s
sys 5m26.169s
```

Should benchmark this to test properly...

**Pull request merged**
